/**
 * Alert type reference with typical causes and resolutions.
 */
export function getAlertsDoc(): string {
  const lines = [
    '# Alert Type Reference',
    '',
    'Comprehensive guide to Datto RMM alert types, typical causes, and resolution strategies.',
    '',
    '---',
    '',
    '## Critical Alerts (Immediate Action Required)',
    '',
    '### Disk Space Low/Critical',
    '',
    '**Threshold:**',
    '- Warning: 80% full',
    '- Critical: 90% full',
    '',
    '**Typical Causes:**',
    '- Log files not rotating',
    '- Windows Update cache accumulation',
    '- Backup files stored locally',
    '- Database/application data growth',
    '',
    '**Resolution:**',
    '1. Run "Disk Cleanup" component',
    '2. Clear Windows Update cache',
    '3. Run "Disk Usage Report" to identify large folders',
    '4. Archive or delete old files',
    '',
    '---',
    '',
    '### Service Down',
    '',
    '**Common Services:**',
    '- SQL Server (MSSQLSERVER)',
    '- IIS Web Server (W3SVC)',
    '- Datto RMM Agent (DattoRMM)',
    '',
    '**Typical Causes:**',
    '- Service crash (application error)',
    '- Resource exhaustion (memory, disk space)',
    '- Dependency failure',
    '- Credential expiration',
    '',
    '**Resolution:**',
    '1. Check device health (disk space, memory)',
    '2. Restart service via run-site-component',
    '3. Get service logs to understand crash',
    '4. Fix underlying issue',
    '',
    '---',
    '',
    '### Device Offline',
    '',
    '**Threshold:** Device hasn\'t contacted RMM in 15+ minutes',
    '',
    '**Typical Causes:**',
    '- Network connectivity lost',
    '- Device powered off',
    '- RMM agent stopped',
    '- Firewall blocking RMM traffic',
    '',
    '**Resolution:**',
    '1. Verify device accessible (ping, RDP)',
    '2. Check RMM agent service status',
    '3. Restart agent if needed',
    '4. Contact site IT if not accessible',
    '',
    '---',
    '',
    '### High CPU Usage',
    '',
    '**Threshold:** CPU sustained above 80% for 15+ minutes',
    '',
    '**Typical Causes:**',
    '- Runaway process',
    '- Antivirus scan running',
    '- Windows Update installation',
    '- Undersized hardware',
    '',
    '**Resolution:**',
    '1. Run "Get Top Processes" component',
    '2. Identify and address culprit',
    '3. If expected task: Wait for completion',
    '4. If chronic: Review hardware capacity',
    '',
    '---',
    '',
    '### High Memory Usage',
    '',
    '**Threshold:** RAM usage sustained above 80%',
    '',
    '**Typical Causes:**',
    '- Memory leak in application',
    '- Too many processes for available RAM',
    '- Database cache growth',
    '- Insufficient RAM for workload',
    '',
    '**Resolution:**',
    '1. Run "Get Top Memory Processes" component',
    '2. Restart memory-consuming services',
    '3. If memory leak: Update application or schedule restarts',
    '4. If undersized: RAM upgrade recommendation',
    '',
    '---',
    '',
    '## Warning Alerts (Monitor, Act If Worsens)',
    '',
    '### Disk Space Warning',
    '**Threshold:** 80% full',
    '**Action:** Monitor for growth, plan cleanup during next maintenance',
    '',
    '### High Temperature',
    '**Threshold:** Above normal operating range',
    '**Action:** Physical inspection, check cooling',
    '',
    '### Certificate Expiring',
    '**Threshold:** SSL/TLS certificate expiring within 30 days',
    '**Action:** Renew certificate, install, restart service',
    '',
    '### Agent Version Outdated',
    '**Threshold:** RMM agent behind latest by 2+ versions',
    '**Action:** Run "Update RMM Agent" component',
    '',
    '---',
    '',
    '## Alert Severity Levels',
    '',
    '### Critical (Red)',
    '**Response Time:** Immediate (within 1 hour)',
    '**Impact:** Service disruption, data loss risk',
    '**Examples:** Disk >90%, service down, device offline, backup failed',
    '',
    '### High (Orange)',
    '**Response Time:** Same day (within 4 hours)',
    '**Impact:** Degraded performance, potential escalation',
    '**Examples:** Disk 80-90%, high CPU/memory, certificate expiring soon',
    '',
    '### Moderate (Yellow)',
    '**Response Time:** Within 1-2 days',
    '**Impact:** Minor issues, informational',
    '**Examples:** Agent outdated, low disk space',
    '',
    '### Low (Blue)',
    '**Response Time:** As convenient',
    '**Impact:** Informational only',
    '**Examples:** Device reboot, configuration changes',
    '',
    '---',
    '',
    '## Alert Patterns & What They Mean',
    '',
    '### Same Alert Across Multiple Devices at One Site',
    '',
    '**Pattern:** "Disk Space Low" on 5+ devices at Acme Corp',
    '',
    '**Likely Cause:** Site-wide issue (backup retention, log policy)',
    '',
    '**Action:** Use get-site-alerts with group_by: "type", then bulk fix',
    '',
    '---',
    '',
    '### Same Alert Type Across Multiple Sites',
    '',
    '**Pattern:** "Service Down: SQL Server" at 3 different sites',
    '',
    '**Likely Cause:** Recent Windows Update broke SQL, systemic issue',
    '',
    '**Action:** Use get-alert-summary with group_by: "site", investigate one, apply fix across affected sites',
    '',
    '---',
    '',
    '### Alert Spikes After Maintenance',
    '',
    '**Pattern:** Sudden increase in alerts after scheduled maintenance',
    '',
    '**Likely Cause:** Maintenance job broke something, configuration change',
    '',
    '**Action:** Use get-account-analytics for trends, check job history, roll back or fix',
    '',
    '---',
    '',
    '### Stale Alerts (Open >24 Hours)',
    '',
    '**Pattern:** Alerts not resolved for extended periods',
    '',
    '**Likely Cause:** Alert not noticed, intermittent issue, low priority',
    '',
    '**Action:** Use get-alert-summary with time_range: "week", review stale alerts',
    '',
    '---',
    '',
    '## When to Use Which Alert Tool',
    '',
    '### get-alert-summary',
    '**Use when:** Want to see patterns and trends',
    '**Grouping by type:** Common alert types across account/site',
    '**Grouping by device:** Which devices have most problems',
    '**Grouping by site:** Which sites need attention',
    '',
    '### investigate-alert',
    '**Use when:** Have specific alert to understand deeply',
    '**Include similar:** Pattern detection across devices',
    '**Gets context:** Recent events, device state, resolution suggestions',
    '',
    '### get-site-alerts',
    '**Use when:** Want site-specific alert overview',
    '**Site-scoped:** Focus on one client',
    '**Grouping options:** Same as get-alert-summary but site-focused',
    '',
    '### get-device-health',
    '**Use when:** Want all alerts for one device',
    '**Device-focused:** Complete health including alerts',
    '**History included:** Shows resolved alerts and patterns',
  ];
  
  return lines.join('\n');
}
