/**
 * Available component catalog with use cases and recommendations.
 */
export function getComponentsDoc(): string {
  const lines = [
    '# Component Catalog',
    '',
    'Reference guide for commonly used components (quick jobs and scripts) in Datto RMM.',
    '',
    '**Note:** This is a representative catalog. Use list-components (Tier 2) to see all available components in your account.',
    '',
    '---',
    '',
    '## Disk & Storage Management',
    '',
    '### Disk Cleanup',
    '**Type:** Quick Job',
    '**Purpose:** Free disk space by removing temporary files, Windows Update cache',
    '**Run Time:** 2-5 minutes',
    '**Requires Admin:** Yes',
    '',
    '**When to use:**',
    '- Disk space critical (>90% full)',
    '- Before running Windows Updates',
    '- Regular maintenance (monthly)',
    '',
    '### Clear Windows Update Cache',
    '**Type:** Script',
    '**Purpose:** Delete cached Windows Update files to free space',
    '**Run Time:** 1-2 minutes',
    '**Requires Admin:** Yes',
    '',
    '**When to use:**',
    '- Disk space issues related to updates',
    '- Windows Update failures (corrupted cache)',
    '- After major updates complete',
    '',
    '### Clear Temp Files',
    '**Type:** Script',
    '**Purpose:** Remove files from temp directories',
    '**Parameters:** days_old (default: 7)',
    '**Run Time:** 1-3 minutes',
    '**Requires Admin:** Yes',
    '',
    '### Disk Usage Report',
    '**Type:** Script',
    '**Purpose:** Generate report of largest folders and files',
    '**Parameters:** drive (optional), top_folders (default: 10)',
    '**Run Time:** 3-10 minutes',
    '',
    '---',
    '',
    '## Windows Update & Patching',
    '',
    '### Windows Updates',
    '**Type:** Quick Job',
    '**Purpose:** Check for and install available Windows Updates',
    '**Run Time:** 10-60+ minutes',
    '**Requires Admin:** Yes',
    '**May Require Reboot:** Yes',
    '',
    '**When to use:**',
    '- Regular patch management',
    '- Security vulnerabilities',
    '- After Patch Tuesday releases',
    '',
    '### Check Pending Reboot',
    '**Type:** Script',
    '**Purpose:** Detect if device needs reboot',
    '**Run Time:** <30 seconds',
    '',
    '### Reset Windows Update Components',
    '**Type:** Script',
    '**Purpose:** Stop services, clear cache, re-register update components',
    '**Run Time:** 3-5 minutes',
    '**Requires Admin:** Yes',
    '',
    '**When to use:**',
    '- Windows Update repeatedly failing',
    '- Update error codes (80240016, etc.)',
    '- Corrupted update database',
    '',
    '---',
    '',
    '## Service Management',
    '',
    '### Restart Service',
    '**Type:** Script',
    '**Purpose:** Stop and start a Windows service',
    '**Parameters:** service_name (required), wait_time (default: 5)',
    '**Run Time:** <1 minute',
    '**Requires Admin:** Yes',
    '',
    '**Common services:**',
    '- DattoRMM - RMM agent',
    '- MSSQLSERVER - SQL Server',
    '- W3SVC - IIS Web Server',
    '- wuauserv - Windows Update',
    '',
    '### Restart RMM Agent',
    '**Type:** Quick Job',
    '**Purpose:** Restart Datto RMM agent service',
    '**Run Time:** <1 minute',
    '**Requires Admin:** Yes',
    '',
    '### Get Service Logs',
    '**Type:** Script',
    '**Purpose:** Retrieve service event logs',
    '**Parameters:** service_name (required), hours_back (default: 24)',
    '**Run Time:** 1-2 minutes',
    '',
    '---',
    '',
    '## Network Diagnostics',
    '',
    '### Network Diagnostic',
    '**Type:** Script',
    '**Purpose:** Comprehensive network health check',
    '**Parameters:** targets (default: ["8.8.8.8", "datto.com"])',
    '**Run Time:** 2-3 minutes',
    '',
    '**Output:** Ping results, DNS resolution, traceroute, gateway info',
    '',
    '### Test Backup Connection',
    '**Type:** Script',
    '**Purpose:** Verify connectivity to backup destination',
    '**Run Time:** <1 minute',
    '',
    '---',
    '',
    '## System Diagnostics',
    '',
    '### Get Top Processes',
    '**Type:** Script',
    '**Purpose:** List processes by CPU usage',
    '**Parameters:** top_n (default: 10)',
    '**Run Time:** <30 seconds',
    '',
    '**When to use:**',
    '- High CPU investigation',
    '- Identifying runaway processes',
    '',
    '### Get Top Memory Processes',
    '**Type:**  Script',
    '**Purpose:** List processes by memory usage',
    '**Parameters:** top_n (default: 10)',
    '**Run Time:** <30 seconds',
    '',
    '**When to use:**',
    '- High memory investigation',
    '- Memory leak detection',
    '',
    '### Check Disk Health',
    '**Type:** Script',
    '**Purpose:** Check SMART status and disk health',
    '**Parameters:** drive (optional)',
    '**Run Time:** 1-2 minutes',
    '**Requires Admin:** Yes',
    '',
    '**When to use:**',
    '- Performance degradation (slow I/O)',
    '- Proactive disk failure prevention',
    '',
    '---',
    '',
    '## Security & Compliance',
    '',
    '### Get Installed Updates',
    '**Type:** Script',
    '**Purpose:** List installed Windows Updates',
    '**Parameters:** days_back (default: 30)',
    '**Run Time:** 1-2 minutes',
    '',
    '### Get Antivirus Status',
    '**Type:** Script',
    '**Purpose:** Check Windows Defender or third-party AV status',
    '**Run Time:** <1 minute',
    '',
    '### Security Scan',
    '**Type:** Quick Job',
    '**Purpose:** Run on-demand antivirus scan',
    '**Parameters:** scan_type (default: "quick")',
    '**Run Time:** 5-60+ minutes',
    '**Requires Admin:** Yes',
    '',
    '---',
    '',
    '## Component Execution Best Practices',
    '',
    '### 1. Test First',
    'Run components on 1-2 pilot devices before broad deployment.',
    '',
    '### 2. Use Scheduling',
    'Schedule resource-intensive jobs for off-hours (10 PM local time, etc.)',
    '',
    '### 3. Check Device Status First',
    'Use list-site-devices with status: "online" before running jobs.',
    '',
    '### 4. Monitor Job Results',
    'Check completion with get-device-health (include_history: true).',
    '',
    '### 5. Handle Failures Gracefully',
    'If job fails:',
    '1. Check device online and accessible',
    '2. Verify permissions (admin rights)',
    '3. Review job parameters',
    '4. Use Tier 2 get-job-stderr for detailed error output',
    '5. Retry with fixes',
    '',
    '---',
    '',
    '## Safety Considerations',
    '',
    '### For Production Servers:',
    '- Use dry-run mode for bulk changes',
    '- Schedule during maintenance windows',
    '- Test on non-critical devices first',
    '- Verify backup before major changes',
    '- Coordinate with stakeholders',
    '',
    '### For Bulk Operations:',
    '- Limited to 50 devices per operation (safety limit)',
    '- Site-scoped (prevents cross-site accidents)',
    '- Dry-run preview before applying',
    '- Offline device warnings',
    '',
    '### For Critical Components:',
    '- Reboot Device: Interrupts users, data loss risk',
    '- Reset Network Settings: Breaks connectivity',
    '- Uninstall Software: May break dependencies',
    '',
    '**Always:** Preview changes, test on pilots, schedule appropriately.',
  ];
  
  return lines.join('\n');
}
