/**
 * Troubleshooting guides organized by symptom/issue type.
 */
export function getTroubleshootingDoc(): string {
  const lines = [
    '# Troubleshooting Guide',
    '',
    'Issue-specific troubleshooting workflows for common problems in MSP environments.',
    '',
    '---',
    '',
    '## Device Offline',
    '',
    '**Symptoms:**',
    '- Device showing as offline in RMM',
    '- Unable to connect remotely',
    '- Jobs failing with "device unreachable"',
    '',
    '**Investigation Tools:**',
    '- get-device-health: Check last seen timestamp and recent activity',
    '- investigate-alert: If offline alert exists, check context and similar alerts',
    '',
    '**Common Causes:**',
    '1. Network issue - Device lost connectivity',
    '2. Agent stopped - Datto RMM agent service not running',
    '3. Device powered off - Maintenance or failure',
    '4. Firewall blocking - New firewall rules blocking RMM traffic',
    '',
    '**Resolution Steps:**',
    '1. Verify device is powered on and on network (ping, remote access)',
    '2. If accessible remotely, check Datto RMM service status',
    '3. Restart agent via run-site-component with "Restart RMM Agent"',
    '4. Check firewall rules if pattern across multiple devices',
    '5. Check proxy configuration if needed (get-site-settings)',
    '',
    '---',
    '',
    '## Disk Space Low/Critical',
    '',
    '**Symptoms:**',
    '- Disk space alerts (critical when >90% full)',
    '- Application errors related to disk writes',
    '- Backup failures due to insufficient space',
    '',
    '**Investigation Tools:**',
    '- get-device-health: Check disk capacity and free space percentage',
    '- diagnose-device-issue with issue: "disk space"',
    '',
    '**Common Causes:**',
    '1. Log files growing - Application logs not rotating',
    '2. Temp files accumulating - Windows Update cache, SQL temp files',
    '3. Backup files - Local backup retention too long',
    '4. User data - Large files in user profiles',
    '5. Database growth - SQL databases expanding',
    '',
    '**Resolution Steps:**',
    '1. Run "Disk Cleanup" component',
    '2. Run "Clear Windows Update Cache" component',
    '3. Run "Clear Temp Files" component',
    '4. Run "Disk Usage Report" to identify space consumers',
    '5. Archive or delete old files',
    '6. If pattern across site: Use get-site-alerts and bulk cleanup',
    '',
    '---',
    '',
    '## High CPU Usage',
    '',
    '**Symptoms:**',
    '- CPU sustained above 80% for extended periods',
    '- System responsiveness degraded',
    '- Applications timing out',
    '',
    '**Investigation Tools:**',
    '- get-device-health: Check current CPU usage',
    '- diagnose-device-issue with issue: "high CPU"',
    '',
    '**Common Causes:**',
    '1. Runaway process - Application stuck in loop',
    '2. Antivirus scan - Full system scan running',
    '3. Windows Update - Update installation in progress',
    '4. Service instability - Service restarting repeatedly',
    '5. Resource exhaustion - Insufficient CPU for workload',
    '',
    '**Resolution Steps:**',
    '1. Run "Get Top Processes" component to identify culprit',
    '2. If antivirus: Wait or reschedule scan',
    '3. If runaway: Restart service',
    '4. If Windows Update: Check status and schedule reboot',
    '5. If service loop: Fix underlying issue (disk space, permissions)',
    '',
    '---',
    '',
    '## Service Down',
    '',
    '**Symptoms:**',
    '- Critical service not running',
    '- Application unavailable',
    '- Service restart alerts',
    '',
    '**Investigation Tools:**',
    '- investigate-alert: Get service down alert details',
    '- diagnose-device-issue with service name',
    '',
    '**Common Causes:**',
    '1. Service crash - Application error or exception',
    '2. Dependency failure - Required service stopped',
    '3. Resource exhaustion - Out of memory, disk space',
    '4. Permission issue - Service account credentials expired',
    '5. Recent change - Update or config broke service',
    '',
    '**Resolution Steps:**',
    '1. Check service dependencies',
    '2. Restart service via run-site-component',
    '3. Get service logs to understand crash',
    '4. Fix underlying issue (disk, memory, permissions)',
    '5. Monitor for restart loops',
    '',
    '---',
    '',
    '## Backup Failures',
    '',
    '**Symptoms:**',
    '- Backup job failed alerts',
    '- Data protection at risk',
    '',
    '**Investigation Tools:**',
    '- get-alert-summary with group_by: "device"',
    '- investigate-alert on specific backup failure',
    '',
    '**Common Causes:**',
    '1. Disk space - Insufficient space for backup files',
    '2. Agent offline - Backup agent not running',
    '3. Network issue - Cannot reach backup destination',
    '4. Permission denied - Backup service account lacks access',
    '5. Destination full - Network storage capacity exceeded',
    '',
    '**Resolution Steps:**',
    '1. Check device health (disk space, agent status)',
    '2. Free space if needed',
    '3. Verify backup agent running',
    '4. Test connectivity to backup destination',
    '5. If pattern: Use get-site-alerts to see extent',
    '',
    '---',
    '',
    '## Tool Selection Guide',
    '',
    '**Starting point:**',
    '- "What needs attention?" → get-account-dashboard',
    '- "Which sites have problems?" → find-sites-with-issues',
    '',
    '**I know the site:**',
    '- "What\'s wrong with this site?" → get-site-health',
    '- "What alerts does site have?" → get-site-alerts',
    '- "Show me devices in site" → list-site-devices',
    '',
    '**I know the device:**',
    '- "What\'s wrong with this device?" → get-device-health',
    '- "Why is device slow/failing?" → diagnose-device-issue',
    '',
    '**I know the alert:**',
    '- "Why did this alert fire?" → investigate-alert',
    '- "Show me alert patterns" → get-alert-summary',
    '',
    '**I need to take action:**',
    '- "Run job on devices" → run-site-component',
    '- "Update multiple devices" → bulk-update-site-devices (dry-run first)',
    '',
    '**I need reports:**',
    '- "How are we doing?" → get-account-analytics',
  ];
  
  return lines.join('\n');
}
